# Generated by Django 6.0.6 on 2026-07-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mineria", "Minería"),
                            ("basura", "Basura"),
                            ("agua", "Agua"),
                            ("aire", "Aire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico"),
                            ("medio", "Medio"),
                            ("bajo", "Bajo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("yanacancha", "Yanacancha"),
                            ("chaupimarca", "Chaupimarca"),
                            ("simonBolivar", "Simón Bolívar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("verified", "Verificada"),
                            ("solved", "Solucionada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("resolution_comment", models.TextField(blank=True, null=True)),
                (
                    "resolution_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
