# Generated by Django 6.0.6 on 2026-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("verified", "Verificada"),
                    ("solved", "Solucionada"),
                    ("dismissed", "Descartada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
