# Generated by Django 6.0.6 on 2026-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alter_alert_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="history_log",
            field=models.TextField(blank=True, null=True),
        ),
    ]
