# Generated by Django 6.0.7 on 2026-07-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_history_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(default=0, help_text='Orden de los puntos para dibujar la ruta.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dumps/')),
                ('schedule', models.CharField(help_text='Horario de recolección/limpieza', max_length=200)),
                ('fill_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('full', 'Lleno')], default='medium', max_length=20)),
                ('type', models.CharField(choices=[('general', 'General'), ('organic', 'Orgánico'), ('recyclable', 'Reciclable'), ('municipalDump', 'Botadero Municipal')], default='municipalDump', max_length=20)),
            ],
        ),
    ]
