# Generated by Django 6.0.7 on 2026-07-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_collectorroutepoint_municipaldump'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alerta Ambiental', 'verbose_name_plural': 'Alertas Ambientales'},
        ),
        migrations.AlterModelOptions(
            name='collectorroutepoint',
            options={'ordering': ['order'], 'verbose_name': 'Punto de Ruta de Recolector', 'verbose_name_plural': 'Puntos de Ruta de Recolector'},
        ),
        migrations.AlterModelOptions(
            name='municipaldump',
            options={'verbose_name': 'Punto de Residuos / Botadero', 'verbose_name_plural': 'Puntos de Residuos / Botaderos'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('mineria', 'Minería'), ('basura', 'Basura'), ('agua', 'Agua'), ('aire', 'Aire')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='district',
            field=models.CharField(choices=[('yanacancha', 'Yanacancha'), ('chaupimarca', 'Chaupimarca'), ('simonBolivar', 'Simón Bolívar')], max_length=30, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='history_log',
            field=models.TextField(blank=True, null=True, verbose_name='Historial de Modificaciones'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolution_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de Resolución'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolution_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen de Resolución'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('critico', 'Crítico'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, verbose_name='Gravedad'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('verified', 'Verificada'), ('solved', 'Solucionada'), ('dismissed', 'Descartada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='collectorroutepoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='collectorroutepoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='collectorroutepoint',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de los puntos para dibujar la ruta.', verbose_name='Orden de Visita'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='fill_level',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('full', 'Lleno')], default='medium', max_length=20, verbose_name='Nivel de Llenado'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dumps/', verbose_name='Imagen Oficial'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Punto'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='schedule',
            field=models.CharField(help_text='Horario de recolección/limpieza', max_length=200, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='municipaldump',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('organic', 'Orgánico'), ('recyclable', 'Reciclable'), ('municipalDump', 'Botadero Municipal')], default='municipalDump', max_length=20, verbose_name='Tipo de Punto'),
        ),
    ]
