# Generated by Django 6.0.7 on 2026-07-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logotipo de la App')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Icono / Favicon')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Modo Mantenimiento Activo')),
                ('maintenance_message', models.TextField(default='El sistema se encuentra en mantenimiento temporal por incidentes. Disculpe las molestias.', verbose_name='Mensaje de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
